---
- name: Make sure prerequisite packages are installed
  ansible.builtin.package:
    name: "{{ __ddclient_prerequisite }}"
    state: present

- name: Download the tar file
  ansible.builtin.get_url:
    url: "{{ __ddclient_download_url }}"
    dest: "{{ __ddclient_download_location }}"
    owner: root
    group: root

- name: Unarchive the archive
  ansible.builtin.unarchive_module:
    src: "{{ __ddclient_download_location }}"
    remote_src: true
    dest: "/tmp"
    owner: root
    group: root
  register: unarchived_folder

- name: Run the configure command
  ansible.builtin.command:
    cmd: ./configure --prefix=/usr --sysconfdir=/etc/ddclient --localstatedir=/var
    chdir: "{{ unarchived_folder.dest }}"
  changed_when: false

- name: Run the make command
  ansible.builtin.command:
    cmd: make
    chdir: "{{ unarchived_folder.dest }}"
  changed_when: false

- name: Run the make check command
  ansible.builtin.command:
    cmd: make check
    chdir: "{{ unarchived_folder.dest }}"
  changed_when: false

- name: Run the make install
  ansible.builtin.command:
    cmd: make install
    chdir: "{{ unarchived_folder.dest }}"
  changed_when: false

- name: Delete downloaded files and archive
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - "{{ unarchived_folder.dest }}"
    - "{{ __ddclient_download_location }}"
