---
# tasks file for ddclient
- name: Install on Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian' and not ddclient_install_from_source

- name: Install on RedHat
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and not ddclient_install_from_source

- name: Install on FreeBSD
  ansible.builtin.include_tasks: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD' and not ddclient_install_from_source

- name: Install from source
  ansible.builtin.include_tasks: install_source.yml
  when: ddclient_install_from_source

- name: Configure ddclient
  ansible.builtin.include_tasks: configure.yml
