---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: True
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
verifier:
  name: ansible
